model_name: "Llama 3.1 8B Instruct VLLM openai-compatible"
python_version: py311
model_metadata:
  example_model_input: {"prompt": "what is the meaning of life"}
  repo_id: meta-llama/Meta-Llama-3.1-8B-Instruct
  openai_compatible: true
  vllm_config: # you can override any vllm config listed in https://docs.vllm.ai/en/stable/models/engine_args.html
    trust_remote_code: true
    tensor_parallel_size: 4
    dtype: auto
    use_v2_block_manager: true
    enforce_eager: true
    distributed_executor_backend: mp # using "ray" might not be supported out of the box
    enable_chunked_prefill: false
    max_model_len: 50000
requirements:
  - vllm==0.5.4
model_cache:
  - repo_id: meta-llama/Meta-Llama-3.1-8B-Instruct
    ignore_patterns:
      - "original/*"
      - "*.pth"
resources:
  accelerator: A10G:4
  use_gpu: true
runtime:
  predict_concurrency: 128
secrets:
  hf_access_token: null
