description: Configuration for the Natural SQL 7B model leveraging Automatic Translation of Natural Language to SQL queries.
python_version: py311
requirements_file: ./requirements.txt
model_metadata:
  example_model_input: '{"questions": ["Show me the day with the most users joining", "What is the ratio of users with gmail addresses vs without?"]}'
resources:
  cpu: "2"
  memory: "8Gi"
  use_gpu: true
  accelerator: A10G
model_cache:
  - repo_id: chatdb/natural-sql-7b
    revision: main
    allow_patterns:
      - "*.bin"
      - "*.json"
    ignore_patterns:
      - "*.tmp"
      - "*.log"
