description: null
environment_variables: {}
live_reload: false
model_name: wizard_vllm
python_version: py311
requirements:
- vllm
- ray
- pyarrow
- pandas>=1.3
resources:
  use_gpu: true
  cpu: "4"
  accelerator: A10G
  memory: 14Gi
secrets:
  hf_token: null
spec_version: '2.0'
system_packages: []
