description: null
environment_variables: {}
live_reload: false
model_name: wizard_vllm
python_version: py311
requirements:
- vllm==0.1.7
- ray==2.7.0
- pyarrow==13.0.0
- pandas>=1.3
resources:
  use_gpu: true
  cpu: "4"
  accelerator: A10G
  memory: 14Gi
secrets:
  hf_token: null
spec_version: '2.0'
system_packages: []
