base_image:
  image: baseten/truss-server-base:3.10-gpu-v0.4.9
  python_executable_path: /usr/bin/python3
model_name: Faster Whisper
model_metadata:
  pretty_name: Whisper
  avatar_url: https://cdn.baseten.co/production/static/openai.png
  cover_image_url: https://cdn.baseten.co/production/static/whisper.png
  example_model_input: {"url": "https://cdn.baseten.co/docs/production/Gettysburg.mp3"}
  model_id: large-v2
  tags:
  - speech-recognition
requirements:
- faster-whisper==0.10.0
resources:
  accelerator: T4
  cpu: 500m
  memory: 512Mi
  use_gpu: true
