base_image:
  image: nvcr.io/nvidia/pytorch:23.11-py3
  python_executable_path: /usr/bin/python3
model_name: Mixtral 8x7B
python_version: py310
requirements:
- vllm==0.2.4
resources:
  accelerator: A100:2
  use_gpu: true
