base_image:
  image: docker.io/baseten/trtllm-server:r23.12_baseten_v0.7.0
  python_executable_path: /usr/bin/python3
description: Generate text from a prompt with this seven billion parameter language model.
model_metadata:
  example_model_input: {"prompt": "What's the meaning of life?"}
  engine_repository: baseten/llama_13b_chat_300x300x128
  pipeline_parallelism: 1
  tags:
  - text-generation
  tensor_parallelism: 1
  tokenizer_repository: NousResearch/Llama-2-13b-chat-hf
model_name: NousResearch/Llama-2-13b-chat-hf
python_version: py311
requirements:
- tritonclient[all]
- transformers==4.34.1
- sentencepiece
resources:
  accelerator: A100
  use_gpu: true
runtime:
  predict_concurrency: 256
  num_workers: 2
