base_image:
  image: public.ecr.aws/q8h3f2p1/baseten/triton_trt_llm:v1
  python_executable_path: /usr/bin/python3
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: trtllm-triton
python_version: py311
requirements: []
resources:
  accelerator: A100
  use_gpu: true
secrets: 
  hf_access_token: 
system_packages: []
runtime:
  predict_concurrency: 1000
