base_image:
  image: baseten/trtllm-build-server:r23.12_baseten_v0.9.0_20240305
  python_executable_path: /usr/bin/python3
description: A TRT-LLM builder truss for Llama-based models. This truss is used to
  build and deploy models that are based on the Llama model architecture and use the TensorRT
  Large Language Model (TRT-LLM) engine.
trt_llm:
  build:
    base_model_architecture: mistral
    huggingface_ckpt_repository: mistralai/Mistral-7B-Instruct-v0.2
    max_input_len: 2000
    max_output_len: 2000
    max_batch_size: 32
    max_beam_width: 1
    plugin_configuration:
      paged_kv_cache: True
environment_variables: {}
external_package_dirs: []
model_metadata:
  tags:
  - text-generation
  - openai-compatible
  tensor_parallelism: 1
  tokenizer_repository: mistralai/Mistral-7B-Instruct-v0.2
model_name: TRT-LLM Model
python_version: py311
requirements:
- tritonclient[all]
- transformers
- jinja2
resources:
  accelerator: H100
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 256
secrets: {}
system_packages: []
