environment_variables:
  COQUI_TOS_AGREED: '1'
external_package_dirs: []
model_metadata: {}
model_name: XTTS Streaming
python_version: py310
requirements_file: ./requirements.txt
resources:
  accelerator: T4
  cpu: '3'
  memory: 10Gi
  use_gpu: true
secrets: {}
system_packages: []
