model_name: mistral-a100-briton
python_version: py310
resources:
  accelerator: A10G
  use_gpu: True
requirements:
  - sentencepiece
  - requests
system_packages:
  - python3.10-venv
secrets:
  hf_access_token: null
trt_llm:
  build:
    max_input_len: 2000
    max_batch_size: 64
    max_beam_width: 1
    max_output_len: 2000
    base_model: llama
    checkpoint_repository:
      repo: mistralai/Mistral-7B-Instruct-v0.2
      source: HF
    tensor_parallel_count: 2
