description: Generate original images from text prompts.
environment_variables: {}
external_package_dirs: []
model_metadata: 
  example_model_input: {"prompt": "A tree in a field under the night sky", "use_refiner": True}
  pretty_name: Stable Diffusion XL
  avatar_url: https://cdn.baseten.co/production/static/stability.png
  cover_image_url: https://cdn.baseten.co/production/static/sd.png
  tags:
  - image-generation
model_name: Stable Diffusion XL
model_framework: custom
model_type: custom
python_version: py39
requirements: 
- transformers
- accelerate
- safetensors
- git+https://github.com/basetenlabs/diffusers.git@9a353290b1497023d4745a719ec02c50f680499a
- invisible-watermark>=0.2.0
- xformers
resources:
  accelerator: A10G
  cpu: 3500m
  memory: 20Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
- libsm6
- libxext6 
