environment_variables: {}
external_package_dirs: []
model_metadata: {}
base_image:
  image: nvcr.io/nvidia/tritonserver:22.11-py3
  python_executable_path: /usr/bin/python3
model_name: lama cleaner
python_version: py310
requirements:
  - xformers==0.0.20
  - lama-cleaner==1.2.3
resources:
  accelerator: A100
  cpu: '1'
  memory: 2Gi
  use_gpu: true
secrets: {}
system_packages:
- ffmpeg
- libsm6
- libxext6 