environment_variables: {}
external_package_dirs: []
base_image:
  image: baseten/truss-server-base:3.10-gpu-v0.4.9
  python_executable_path: /usr/bin/python3
model_name: Faster Whisper
python_version: py39
model_metadata:
  pretty_name: Whisper
  avatar_url: https://cdn.baseten.co/production/static/openai.png
  cover_image_url: https://cdn.baseten.co/production/static/whisper.png
  example_model_input: {"url": "https://cdn.baseten.co/docs/production/Gettysburg.mp3"}
  tags:
  - speech-recognition
model_cache:
- repo_id: guillaumekln/faster-whisper-large-v2
requirements:
- faster-whisper
resources:
  accelerator: A10G
  cpu: 500m
  memory: 512Mi
  use_gpu: true
secrets: {}
system_packages: []
