base_image:
  image: nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
  python_executable_path: /usr/bin/python3
model_metadata:
  tags:
  - text-generation
  tensor_parallelism: 1
python_version: py311
requirements:
- tritonclient[all]
- transformers==4.34.1
resources:
  use_gpu: true
  accelerator: A100
runtime:
  predict_concurrency: 256
