base_image:
  image: nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
  python_executable_path: /usr/bin/python3
environment_variables: {}
external_package_dirs: []
model_metadata:
  tensor_parallelism: 1
  engine_repository: "baseten/llama2-7b-chat-hf-fp16-tp1-bs-256"
  tokenizer_repository: "NousResearch/Llama-2-7b-chat-hf"
model_name: trtllm-trtllm
python_version: py311
requirements:
- tritonclient[all]
resources:
  accelerator: A100
  use_gpu: true
secrets: {}
system_packages: []
runtime:
  predict_concurrency: 256