environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Playground v2 1024px Aesthetic Model
python_version: py311
requirements:
  - torch==2.1.1
  - transformers==4.35.2
  - diffusers==0.24.0
  - accelerate==0.25.0
model_cache:
- repo_id: "playgroundai/playground-v2-1024px-aesthetic"
  allow_patterns:
    - "*.json"
    - "*.txt"
    - "*.fp16.safetensors"
resources:
  accelerator: A10G
  cpu: '3'
  memory: 15Gi
  use_gpu: true
secrets: {}
system_packages: []
