environment_variables: {}
external_package_dirs: []
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  repo_id: nvidia/Llama3-ChatQA-1.5-70B
  tags:
  - text-generation
model_name: Llama3-ChatQA-1.5-70B
python_version: py310
model_cache:
  - repo_id: nvidia/Llama3-ChatQA-1.5-70B
requirements:
  - accelerate
  - einops
  - transformers
  - torch
resources:
  accelerator: A100:2
  use_gpu: true
secrets: {}
system_packages: []
