base_image:
  image: nvcr.io/nvidia/pytorch:23.11-py3
  python_executable_path: /usr/bin/python
description: Generate original images from text prompts.
environment_variables: 
  HF_HUB_ENABLE_HF_TRANSFER: 1
external_package_dirs: []
model_metadata:
  example_model_input: {"prompt": "A tree in a field under the night sky", "use_refiner": True}
  pretty_name: Stable Diffusion XL
  avatar_url: https://cdn.baseten.co/production/static/stability.png
  cover_image_url: https://cdn.baseten.co/production/static/sd.png
  tags:
  - image-generation
model_name: Stable Diffusion XL - TensorRT
model_framework: custom
model_type: custom
python_version: py39
requirements:
- accelerate
- colored
- controlnet_aux==0.0.6
- cuda-python
- diffusers==0.23.1
- ftfy
- matplotlib
- nvtx
- onnx==1.14.0
- onnxruntime==1.15.1
- opencv-python==4.8.0.74
- scipy
- transformers==4.31.0
- hf_transfer
- --extra-index-url https://pypi.ngc.nvidia.com
- onnx-graphsurgeon>=0.3.27
- polygraphy
- --extra-index-url https://pypi.nvidia.com
- tensorrt==8.6.1.post1
resources:
  accelerator: A100
  cpu: 10000m
  memory: 120Gi
  use_gpu: true
secrets: {}
runtime:
  predict_concurrency: 1
