apply_library_patches: true
base_image:
  image: baseten/trtllm-server:r23.12_baseten_v0.9.0.dev2024022000
  python_executable_path: /usr/bin/python3
build:
  arguments:
    engine_repository: baseten/mistral_fp8_tp8_i2048_o2048_bs128-tllm_0.9.0.dev2024022000
    pipeline_parallel_count: 1
    tensor_parallel_count: 8
    tokenizer_repository: mistralai/Mistral-7B-Instruct-v0.2
bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this seven billion parameter language
  model.
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_cache: []
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  tags:
  - text-generation
  - openai-compatible
model_module_dir: model
model_name: Mistral 8
model_type: Model
python_version: py311
requirements:
- tritonclient[all]
- transformers
- jinja2
- TensorRT==9.3.0.post12.dev1
resources:
  accelerator: H100:8
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 512
secrets: {}
