apply_library_patches: true
base_image:
  image: baseten/trtllm-server:r23.12_baseten_v0.9.0.dev2024022000
  python_executable_path: /usr/bin/python3
build:
  arguments:
    engine_repository: baseten/solar_fp8_tp1_i6000_o1000_bs64-tllm_0.9.0.dev2024022000
    pipeline_parallel_count: 1
    tensor_parallel_count: 1
    tokenizer_repository: NousResearch/Nous-Hermes-2-SOLAR-10.7B
bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this seven billion parameter language
  model.
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_cache: []
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  tags:
  - text-generation
  - openai-compatible
model_module_dir: model
model_name: Solar
model_type: Model
python_version: py311
requirements:
- tritonclient[all]
- transformers
- jinja2
resources:
  accelerator: H100:1
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 512
secrets: {}
