description: Generate text with an instruction-tuned version of Mistral 7B.
model_metadata:
  example_model_input: {"messages": [{"role": "user", "content": "What is the mistral wind?"}]}
  pretty_name: Mistral 7B Chat
  avatar_url: https://cdn.baseten.co/production/static/explore/mistral_logo.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/mistral.png
  tags:
  - text-generation
model_name: Mistral 7B Chat
python_version: py311
requirements:
- sentencepiece
- accelerate
- transformers==4.34.0
- torch==2.0.1
resources:
  accelerator: A10G
  use_gpu: true
  memory: 25Gi
secrets: {}
