apply_library_patches: true
base_image:
  image: docker.io/baseten/triton_trt_llm:9691e12bce7ae1c126c435a049eb516eb119486c
  python_executable_path: /usr/bin/python3
build:
  arguments:
    engine_repository: aspctu/fp8_mistral_medusa
    pipeline_parallel_count: 1
    tensor_parallel_count: 1
    tokenizer_repository: mistral-community/Mistral-7B-v0.2
bundled_packages_dir: packages
data_dir: data
description: Generate text from a prompt with this seven billion parameter language model.
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  tags:
  - text-generation
  - openai-compatible
model_module_dir: model
model_name: medusa-model
model_type: Model
python_version: py311
requirements:
- tritonclient[all]
- transformers
- jinja2
resources:
  accelerator: H100:1
  use_gpu: true
runtime:
  num_workers: 1
  predict_concurrency: 512
