base_image:
  image: docker.io/baseten/triton_trt_llm:v1
  python_executable_path: /usr/bin/python3
environment_variables: {}
external_package_dirs: []
model_metadata:
  tensor_parallelism: 1
  tokenizer_repository: "NousResearch/Llama-2-7b-chat-hf"
model_name: trtllm-triton
python_version: py311
requirements: []
resources:
  accelerator: A100
  use_gpu: true
secrets: {}
system_packages: []
runtime:
  predict_concurrency: 256
